---

- name: Terminate a cluster
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - region: 'us-east-1'
  # The following vars must be overridden
  # name: ETL
  tasks:
    - name: terminate the EMR cluster
      emr:
        name: "{{ name }}"
        region: "{{ region }}"
        state: absent
      register: result
      retries: 3
      delay: 5  # Seconds of delay between retries.
      until: result is success  # Stop condition for retries.
